package com.mypieceofcode.rpgapi.exceptions

enum class ErrorCode {
    ABILITY_EMPTY_NAME,
    ABILITY_EMPTY_DESCRIPTION,
    ABILITY_EMPTY_ID,
    ABILITY_ALREADY_EXISTS,
    ABILITY_NOT_FOUND,

    SKILL_EMPTY_ID,
    SKILL_EMPTY_NAME,
    SKILL_EMPTY_DESCRIPTION,
    SKILL_INVALID_TRAIT,
    SKILL_INVALID_TYPE,
    SKILL_ALREADY_EXISTS,
    SKILL_NOT_FOUND,

    ITEM_EMPTY_ID,
    ITEM_EMPTY_NAME,
    ITEM_EMPTY_DESCRIPTION,
    ITEM_EMPTY_PRICE,
    ITEM_EMPTY_AVAILABILITY,
    ITEM_INVALID_PRICE,
    ITEM_INVALID_AVAILABILITY
}